// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgpgxpperonqyivoevbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNncGd4cHBlcm9ucXlpdm9ldmJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MzA3NTAsImV4cCI6MjA3MDAwNjc1MH0.yy_fb8HVV-dW3jhF9ClcAx0GD3X_57CzHee2kWXy9pA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});